export const AUTH_COPY = {
  login: {
    headline: "The Complete Operating System for Photographers",
    subheadline:
      "Manage bookings, clients, payments, schedules, and gallery delivery from one powerful platform.",
    title: "Welcome back",
    portalBadge: "Photographer & Client Portal",
    subtitle: "Sign in to access your Shutterdesk account",
    backToWebsite: "Back to Website",
    securityNote: "Your data is encrypted and securely stored.",
    emailPlaceholder: "imani.uwase@shutterdesk.rw",
    rememberMe: "Remember me for 30 days",
    signIn: "Sign In",
    google: "Continue with Google",
    noAccount: "Don't have an account?",
    createAccount: "Create Account",
  },
  register: {
    headline: "Join Photographers Managing Their Entire Business in One Place",
    subheadline:
      "Create your Shutterdesk account and manage bookings, payments, clients, and galleries from one centralized platform.",
    title: "Create your account",
    subtitle: "Start your Shutterdesk journey today",
    backToWebsite: "Back to Website",
    securityNote: "Your data is encrypted and securely stored.",
    fullNamePlaceholder: "Immaculée Niyonsaba",
    emailPlaceholder: "imani.uwase@shutterdesk.rw",
    phonePlaceholder: "+250 788 000 000",
    confirmPasswordLabel: "Confirm Password",
    termsPrefix: "I agree to the",
    termsOfService: "Terms of Service",
    termsAnd: "and",
    privacyPolicy: "Privacy Policy",
    createAccount: "Create Account",
    google: "Continue with Google",
    hasAccount: "Already have an account?",
    signIn: "Sign In",
  },
  logout: "Log Out",
  logoutSuccess: "You have been logged out successfully",
} as const;
