export type ClientBookingFilter = "all" | "pending" | "confirmed" | "completed";

export const CLIENT_BOOKINGS_COPY = {
  title: "My Bookings",
  subtitle: "Track your sessions and project progress.",
  searchPlaceholder: "Search by package or date...",
  filters: {
    all: "All",
    pending: "Pending",
    confirmed: "Confirmed",
    completed: "Completed",
  },
  columns: {
    package: "Package",
    date: "Date",
    status: "Status",
    payment: "Payment",
    actions: "Actions",
  },
  viewDetails: "View details",
  uploadReceipt: "Upload receipt",
  viewGallery: "View gallery",
  noResults: "No bookings match your search.",
  emptyTitle: "No bookings yet",
  emptyBody: "Book your first session to get started with Imani Uwase Photography.",
  bookSession: "Book a session",
  nextSession: "Next Session",
  noUpcomingSession: "No upcoming session",
  detail: {
    progress: "Booking Progress",
    timeline: "Activity Timeline",
    sessionDetails: "Session Details",
    packageDetails: "Package Details",
    paymentStatus: "Payment Status",
    venue: "Venue",
    dateTime: "Date & Time",
    amountPaid: "Amount Paid",
    depositDue: "Deposit Due",
    outstandingBalance: "Outstanding Balance",
    paidInFull: "Paid in Full",
    noOutstandingBalance: "No Outstanding Balance",
    totalPrice: "Total Price",
    payNow: "Make a Payment",
    payInFull: (amount: string) => `Pay full amount (${amount})`,
    securedBy: "Secured by Shutterdesk Pay",
    yourProfile: "Your Profile",
    contactEmail: "Email",
    contactPhone: "Phone",
    notProvided: "Not provided",
    profileSyncedHint: "From your Shutterdesk account",
    primaryVenue: "Primary Venue",
    uploadReceipt: "Upload Receipt",
    viewGallery: "View Gallery",
    backToBookings: "My Bookings",
    status: {
      pendingVerification: "Awaiting Verification",
      confirmed: "Confirmed",
      pending: "Pending",
      completed: "Completed",
      cancelled: "Cancelled",
    },
  },
  statusLabels: {
    confirmed: "Confirmed",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
  },
  paymentLabels: {
    paid: "Paid",
    partial: "Partial",
    unpaid: "Unpaid",
  },
  notFound: "We couldn't find that booking.",
  backToBookings: "Back to My Bookings",
} as const;
