export const CLIENT_GALLERIES_COPY = {
  title: "My Galleries",
  subtitle: "View and download your private photo collections.",
  searchPlaceholder: "Search galleries...",
  viewGallery: "View Gallery",
  photos: (count: number) => `${count} photos`,
  processingSession: "Processing session...",
  badge: {
    delivered: "Delivered",
    ready: "Ready to view",
    editing: "Being prepared",
  },
  delivered: "Delivered",
  ready: "Ready to view",
  editing: "Being prepared",
  noResults: "No galleries found.",
  newSession: {
    title: "New Session",
    body: "Book your next shoot to start a new gallery.",
  },
  detail: {
    backToGalleries: "My Galleries",
    download: "Download",
    downloadGallery: "Download Gallery",
    preparingZip: "Preparing ZIP...",
    preparingZipProgress: (completed: number, total: number) =>
      `Preparing ZIP (${completed}/${total})...`,
    downloadFailed: "Unable to download gallery. Please try again.",
    viewAlbum: "View album",
    galleryInformation: "Gallery Information",
    curatedHighlights: "Curated Highlights",
    curatedSubtitle: "Selected by the photographer",
    newContent: "New content",
    favorite: "Favorite",
    accessPin: "Access PIN",
    expires: "Link expires",
    downloadsEnabled: "Downloads enabled",
    downloadsDisabled: "Downloads not available yet",
    deliveryInfo: "Gallery Access",
    noPhotosFound: "No photos in this gallery yet.",
    loadMore: "Load more photos",
    downloadPhoto: "Download photo",
    viewPhoto: "View photo",
    tapToView: "Tap any photo to view full screen",
    pinProtectedTitle: "PIN protected gallery",
    pinProtectedBody:
      "Your photographer secured this gallery with an access PIN. Enter the PIN they shared with you to view your photos.",
    enterPin: "Gallery access PIN",
    pinPlaceholder: "Enter PIN",
    unlockGallery: "Unlock gallery",
    verifyingPin: "Verifying…",
    incorrectPin: "Incorrect PIN. Please try again.",
    pinRequired: "PIN required",
    privateAccess: "Private access",
    galleryExpired: "This gallery link has expired.",
    expiredTitle: "Gallery unavailable",
  },
  notFound: "We couldn't find that gallery.",
  backToGalleries: "Back to My Galleries",
} as const;

export type ClientGalleryBadgeKey = keyof typeof CLIENT_GALLERIES_COPY.badge;
