export type ClientBookingFilter = "all" | "pending" | "confirmed" | "completed";

export const CLIENT_BOOKINGS_COPY = {
  title: "My bookings",
  subtitle: "Track your sessions and project progress.",
  searchPlaceholder: "Search by package or date...",
  filters: {
    all: "All",
    pending: "Pending",
    confirmed: "Confirmed",
    completed: "Completed",
  },
  columns: {
    package: "Package",
    date: "Date",
    status: "Status",
    payment: "Payment",
    actions: "Actions",
  },
  viewDetails: "View details",
  uploadReceipt: "Upload receipt",
  viewGallery: "View gallery",
  noResults: "No bookings match your search.",
  emptyTitle: "No bookings yet",
  emptyBody: "Book your first session to get started with imani uwase photography.",
  bookSession: "Book a session",
  nextSession: "Next session",
  noUpcomingSession: "No upcoming session",
  detail: {
    progress: "Booking progress",
    timeline: "Activity timeline",
    sessionDetails: "Session details",
    packageDetails: "Package details",
    paymentStatus: "Payment status",
    venue: "Venue",
    dateTime: "Date & time",
    amountPaid: "Amount paid",
    depositDue: "Deposit due",
    outstandingBalance: "Outstanding balance",
    paidInFull: "Paid in Full",
    noOutstandingBalance: "No outstanding balance",
    totalPrice: "Total price",
    payNow: "Make a payment",
    payInFull: (amount: string) => `Pay full amount (${amount})`,
    securedBy: "Secured by Shutterdesk Pay",
    yourProfile: "Your profile",
    contactEmail: "Email",
    contactPhone: "Phone",
    notProvided: "Not provided",
    profileSyncedHint: "From your Shutterdesk account",
    primaryVenue: "Primary venue",
    uploadReceipt: "Upload receipt",
    viewGallery: "View gallery",
    backToBookings: "My bookings",
    status: {
      pendingVerification: "Awaiting verification",
      confirmed: "Confirmed",
      pending: "Pending",
      completed: "Completed",
      cancelled: "Cancelled",
    },
  },
  statusLabels: {
    confirmed: "Confirmed",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
  },
  paymentLabels: {
    paid: "Paid",
    partial: "Partial",
    unpaid: "Unpaid",
  },
  notFound: "We couldn't find that booking.",
  backToBookings: "Back to my bookings",
} as const;
