import { formatRwf } from "@/lib/currency";

export const SERVICE_CREATE_COPY = {
  breadcrumbServices: "Services",
  breadcrumbCurrent: "Create new",
  title: "Create new package",
  subtitle:
    "Build photography packages that clients can book through your platform.",
  packageInformation: "Package information",
  packageName: "Package name",
  packageNamePlaceholder: "e.g. Minimalist Studio Session",
  category: "Category",
  status: "Status",
  statusDescription: "Set package visibility to clients",
  active: "Active",
  coverImage: "Cover image",
  coverDropTitle: "Drop your cover image here",
  coverDropHint: "PNG, JPG or WEBP (Max 5MB)",
  pricing: "Pricing",
  packagePrice: "Package price",
  depositPercentage: "Deposit percentage",
  currency: "Currency",
  sessionDetails: "Session details",
  sessionDuration: "Session duration",
  numberOfPhotographers: "Number of photographers",
  locationType: "Location type",
  deliverables: "Deliverables",
  editedPhotos: "Number of edited photos",
  revisions: "Number of revisions",
  onlineGallery: "Online gallery included",
  printDelivery: "Print delivery included",
  commercialLicense: "Full commercial license",
  description: "Description",
  packageDescription: "Package description",
  packageDescriptionPlaceholder:
    "Briefly describe what makes this package unique...",
  whatsIncluded: "What's included",
  addCustom: "Add custom",
  addItem: "Add item",
  additionalNotes: "Additional notes",
  additionalNotesPlaceholder:
    "e.g. Travel fees apply for locations outside Kigali city limits...",
  packagePreview: "Package preview",
  preview: "Preview",
  publishPackage: "Publish package",
  saveAsDraft: "Save as draft",
  draftSaved: "Draft saved. You can return anytime to finish and publish.",
  publishNameRequired: "Please enter a package name before publishing.",
  untitledPackageName: "Untitled package",
  autoSaved: "Changes auto-saved 2 mins ago",
  editBreadcrumbCurrent: "Edit package",
  editTitle: "Edit service package",
  editSubtitle: "Update your photography package details and deliverables.",
  saveChanges: "Save changes",
  cancel: "Cancel",
  notFound: "Service package not found.",
  lastUpdated: "Last updated 2 mins ago",
  proTipTitle: "Pro tip: deliverables",
  proTipBody:
    "Packages with 'Online gallery' selected see 35% higher booking rates as it provides immediate value to your clients.",
  defaultPackageName: "Package name",
  priceDisplay: (price: number) => formatRwf(price),
  categories: {
    wedding: "Wedding",
    portrait: "Portrait",
    commercial: "Commercial",
    editorial: "Editorial",
  },
  durations: {
    "30min": "30 Minutes",
    "1hr": "1 Hour",
    "2hr": "2 Hours",
    "4hr": "4 Hours",
    fullday: "Full day",
  },
  locationTypes: {
    studio: "Studio",
    outdoor: "Outdoor",
    client: "Client location",
    hybrid: "Hybrid",
  },
  currencies: {
    rwf: "RWF - rwandan franc",
  },
  defaultIncludes: [
    "Professional retouching",
    "Online private gallery",
    "Full printing rights",
  ],
} as const;
