export const GALLERIES_COPY = {
  title: "Galleries",
  totalCount: (count: number) => `${count} Galleries in total`,
  addNewGallery: "Add New Gallery",
  searchPlaceholder: "Search galleries...",
  category: "Category",
  status: "Status",
  sortBy: "Sort by",
  all: "All",
  uploaded: "Uploaded",
  client: (name: string) => `Client: ${name}`,
  photos: (count: number) => `${count} Photos`,
  loadMore: "Load More Galleries",
  noGalleriesFound: "No galleries found for this search.",
  noClientGalleries: (clientName: string) =>
    `No galleries for ${clientName} yet.`,
  showingClientGalleries: (clientName: string) =>
    `Showing galleries for ${clientName}`,
  clearClientFilter: "Show all galleries",
  share: "Share",
  edit: "Edit",
  view: "View",
  moreActions: "More actions",
  categories: {
    wedding: "Wedding",
    portrait: "Portrait",
    graduation: "Graduation",
    commercial: "Commercial",
  },
  statuses: {
    published: "Published",
    draft: "Draft",
    archived: "Archived",
  },
  workflowStatus: {
    delivered: "Delivered",
    ready: "Ready",
    editing: "Editing",
  },
  footerStatus: {
    delivered: "Shared with Client",
    ready: "Awaiting Review",
    editing: "Offline Draft",
  },
  sortOptions: {
    dateUploaded: "Date Uploaded",
    name: "Name",
    photoCount: "Photo Count",
  },
  detail: {
    back: "Back to galleries",
    client: (name: string) => `Client: ${name}`,
    preview: "Preview",
    share: "Share",
    uploadPhotos: "Upload Photos",
    loadMorePhotos: "Load More Photos",
    showingPhotos: (shown: number, total: number) =>
      `Showing ${shown} of ${total} photos`,
    notFound: "Gallery not found.",
    backToGalleries: "Back to Galleries",
    noPhotosFound: "No photos found for this gallery.",
    downloadPhoto: "Download photo",
    viewPhoto: "View photo",
    editPhoto: "Edit photo details",
    deletePhoto: "Delete photo",
    replacePhoto: "Replace photo",
    moveEarlier: "Move earlier",
    moveLater: "Move later",
    photoAltLabel: "Photo label",
    savePhotoDetails: "Save details",
    deletePhotoConfirm: "Remove this photo from the gallery?",
    photos: {
      deleted: "Photo removed",
      updated: "Photo details saved",
      reordered: "Photo order updated",
    },
    storageUsed: (used: number, total: number) => `${used} GB / ${total} GB used`,
    tabs: {
      photos: "Photos",
      delivery: "Delivery",
      analytics: "Analytics",
      settings: "Settings",
    },
    tabPanels: {
      delivery: {
        statusTitle: "Delivery Status",
        timelineTitle: "Delivery Timeline",
        accessTitle: "Client Access",
        permissionsTitle: "Download Permissions",
        notesTitle: "Delivery Notes",
        privateLink: "Private gallery link",
        accessPin: "Access PIN",
        accessPinPlaceholder: "Set a 4–8 digit PIN",
        expiresAt: "Link expires",
        copyLink: "Copy Link",
        copied: "Copied!",
        sendToClient: "Send to Client",
        downloadEnabled: "Allow downloads",
        downloadEnabledHint: "Let clients save photos from the gallery",
        highResDownloads: "High-resolution files",
        highResDownloadsHint: "Enable full-size JPEG downloads",
        watermarkEnabled: "Watermark previews",
        watermarkEnabledHint: "Apply watermark until final delivery",
        clientNotified: "Client notified",
        clientNotifiedHint: "Send email when gallery is ready",
        saveChanges: "Save Delivery Settings",
        saved: "Delivery settings saved",
        proTipTitle: "Pro Tip: Delivery",
        proTipBody:
          "Galleries with watermarked previews see 40% fewer premature download requests while still keeping clients engaged.",
      },
      analytics: {
        totalViews: "Total Views",
        downloads: "Downloads",
        favorites: "Favorites",
        uniqueVisitors: "Unique Visitors",
        viewsTrend: "+12% this week",
        downloadsTrend: "+8% this week",
        favoritesTrend: "+5% this week",
        visitorsTrend: "+9% this week",
        weeklyViews: "Views This Week",
        topPhotos: "Top Performing Photos",
        engagement: "Engagement Rate",
        engagementHint: "Based on views, favorites, and downloads",
        avgSession: "Avg. session",
        activityLog: "Activity Log",
        noActivity: "No activity recorded for this gallery yet.",
        columns: {
          photo: "Photo",
          views: "Views",
          downloads: "Downloads",
        },
      },
      settings: {
        visibilityTitle: "Visibility & Access",
        preferencesTitle: "Gallery Preferences",
        urlTitle: "Gallery URL",
        visibility: "Gallery visibility",
        visibilityOptions: {
          public: "Public — anyone with the link",
          private: "Private — invited clients only",
          password: "Password protected",
        },
        expirationDate: "Expiration date",
        accessPin: "Access PIN",
        accessPinPlaceholder: "Set a 4–8 digit PIN",
        accessPinHint: "Clients must enter this PIN before viewing the gallery.",
        customSlug: "Custom URL slug",
        galleryStatus: "Gallery status",
        statusOptions: {
          published: "Published",
          draft: "Draft",
          archived: "Archived",
        },
        allowSharing: "Allow sharing",
        allowSharingHint: "Clients can share the gallery link with guests",
        allowFavorites: "Allow favorites",
        allowFavoritesHint: "Clients can mark photos as favorites",
        showPhotographerCredit: "Show photographer credit",
        showPhotographerCreditHint: "Display your studio name on the gallery",
        emailNotifications: "Email notifications",
        emailNotificationsHint: "Get notified on views and downloads",
        saveChanges: "Save Changes",
        saved: "Settings saved",
      },
    },
    lightbox: {
      close: "Close viewer",
      previous: "Previous photo",
      next: "Next photo",
      counter: (current: number, total: number) => `${current} / ${total}`,
      viewPhoto: (index: number) => `View photo ${index}`,
    },
    sidebar: {
      clientInfo: "Client Info",
      summary: "Summary",
      shootDate: "Shoot Date",
      location: "Location",
      notifyClient: "Notify Client",
      exportReport: "Export Report",
      archiveGallery: "Archive Gallery",
      activityLog: "Activity Log",
      viewProfile: "View Profile",
      viewAllActivity: "View All Activity",
      noActivity: "No client activity recorded yet.",
      notifySuccess: "Client notified",
      notifySuccessDescription: "An in-app notification was sent to the client.",
      exportSuccess: "Report exported",
      exportSuccessDescription: "Gallery analytics report downloaded.",
      archiveSuccess: "Gallery archived",
      archiveSuccessDescription: "This gallery is no longer visible to clients.",
      archiveConfirm: "Archive this gallery? Clients will lose access immediately.",
      archiveAlready: "This gallery is already archived.",
    },
  },
} as const;

export type GalleryCategoryFilter =
  | "all"
  | "wedding"
  | "portrait"
  | "graduation"
  | "commercial";

export type GalleryStatusFilter = "all" | "published" | "draft" | "archived";

export type GallerySortOption = "dateUploaded" | "name" | "photoCount";

export type GalleryDetailTab = "photos" | "delivery" | "analytics" | "settings";
