export const ADD_CLIENT_COPY = {
  title: "Add new client",
  description:
    "Create a client profile to start managing bookings, payments, and galleries.",
  personalInformation: "Personal information",
  required: "Required",
  fullName: "Full name",
  fullNamePlaceholder: "e.g. Grace Uwera",
  emailAddress: "Email address",
  emailPlaceholder: "grace.uwera@gmail.com",
  phoneNumber: "Phone number",
  phonePlaceholder: "+250 788 000 000",
  clientClassification: "Client classification",
  clientCategory: "Client category",
  categoryPlaceholder: "Select a category...",
  optionalInformation: "Optional information",
  address: "Address",
  addressPlaceholder: "e.g. Nyarutarama, Kigali",
  notes: "Internal notes",
  notesPlaceholder: "Add any internal notes about this client...",
  cancel: "Cancel",
  createClient: "Create client",
  categories: {
    wedding: "Wedding",
    commercial: "Commercial",
    portrait: "Portrait",
    editorial: "Editorial",
  },
} as const;
