export const GALLERIES_COPY = {
  title: "Galleries",
  totalCount: (count: number) => `${count} Galleries in total`,
  addNewGallery: "Add new gallery",
  searchPlaceholder: "Search galleries...",
  category: "Category",
  status: "Status",
  sortBy: "Sort by",
  all: "All",
  uploaded: "Uploaded",
  client: (name: string) => `Client: ${name}`,
  photos: (count: number) => `${count} Photos`,
  loadMore: "Load more galleries",
  noGalleriesFound: "No galleries found for this search.",
  noClientGalleries: (clientName: string) =>
    `No galleries for ${clientName} yet.`,
  showingClientGalleries: (clientName: string) =>
    `Showing galleries for ${clientName}`,
  clearClientFilter: "Show all galleries",
  share: "Share",
  edit: "Edit",
  view: "View",
  moreActions: "More actions",
  categories: {
    wedding: "Wedding",
    portrait: "Portrait",
    graduation: "Graduation",
    commercial: "Commercial",
  },
  statuses: {
    published: "Published",
    draft: "Draft",
    archived: "Archived",
  },
  workflowStatus: {
    delivered: "Delivered",
    ready: "Ready",
    editing: "Editing",
  },
  footerStatus: {
    delivered: "Shared with client",
    ready: "Awaiting review",
    editing: "Offline draft",
  },
  sortOptions: {
    dateUploaded: "Date uploaded",
    name: "Name",
    photoCount: "Photo count",
  },
  detail: {
    back: "Back to galleries",
    client: (name: string) => `Client: ${name}`,
    preview: "Preview",
    share: "Share",
    uploadPhotos: "Upload photos",
    loadMorePhotos: "Load more photos",
    showingPhotos: (shown: number, total: number) =>
      `Showing ${shown} of ${total} photos`,
    notFound: "Gallery not found.",
    backToGalleries: "Back to galleries",
    noPhotosFound: "No photos found for this gallery.",
    downloadPhoto: "Download photo",
    viewPhoto: "View photo",
    editPhoto: "Edit photo details",
    deletePhoto: "Delete photo",
    replacePhoto: "Replace photo",
    moveEarlier: "Move earlier",
    moveLater: "Move later",
    photoAltLabel: "Photo label",
    savePhotoDetails: "Save details",
    deletePhotoConfirm: "Remove this photo from the gallery?",
    photos: {
      deleted: "Photo removed",
      updated: "Photo details saved",
      reordered: "Photo order updated",
    },
    photoCount: (count: number) =>
      `${count} ${count === 1 ? "photo" : "photos"}`,
    tabs: {
      photos: "Photos",
      delivery: "Delivery",
      analytics: "Analytics",
      settings: "Settings",
    },
    tabPanels: {
      delivery: {
        statusTitle: "Delivery status",
        timelineTitle: "Delivery timeline",
        accessTitle: "Client access",
        permissionsTitle: "Download permissions",
        notesTitle: "Delivery notes",
        privateLink: "Private gallery link",
        accessPin: "Access PIN",
        accessPinPlaceholder: "Set a 4–8 digit PIN",
        expiresAt: "Link expires",
        copyLink: "Copy link",
        copied: "Copied!",
        sendToClient: "Send to client",
        downloadEnabled: "Allow downloads",
        downloadEnabledHint: "Let clients save photos from the gallery",
        highResDownloads: "High-resolution files",
        highResDownloadsHint: "Enable full-size JPEG downloads",
        watermarkEnabled: "Watermark previews",
        watermarkEnabledHint: "Apply watermark until final delivery",
        clientNotified: "Client notified",
        clientNotifiedHint: "Send email when gallery is ready",
        saveChanges: "Save delivery settings",
        saved: "Delivery settings saved",
        proTipTitle: "Pro tip: delivery",
        proTipBody:
          "Galleries with watermarked previews see 40% fewer premature download requests while still keeping clients engaged.",
      },
      analytics: {
        totalViews: "Total views",
        downloads: "Downloads",
        activityLog: "Activity log",
        noActivity: "No activity recorded for this gallery yet.",
        limitedTrackingNote:
          "Views and downloads are counted per gallery. Per-visitor and per-photo activity is not tracked yet.",
      },
      settings: {
        visibilityTitle: "Visibility & access",
        preferencesTitle: "Gallery preferences",
        urlTitle: "Gallery URL",
        visibility: "Gallery visibility",
        visibilityOptions: {
          public: "Public — anyone with the link",
          private: "Private — invited clients only",
          password: "Password protected",
        },
        expirationDate: "Expiration date",
        accessPin: "Access PIN",
        accessPinPlaceholder: "Set a 4–8 digit PIN",
        accessPinHint: "Clients must enter this PIN before viewing the gallery.",
        customSlug: "Custom URL slug",
        galleryStatus: "Gallery status",
        statusOptions: {
          published: "Published",
          draft: "Draft",
          archived: "Archived",
        },
        allowSharing: "Allow sharing",
        allowSharingHint: "Clients can share the gallery link with guests",
        allowFavorites: "Allow favorites",
        allowFavoritesHint: "Clients can mark photos as favorites",
        showPhotographerCredit: "Show photographer credit",
        showPhotographerCreditHint: "Display your studio name on the gallery",
        emailNotifications: "Email notifications",
        emailNotificationsHint: "Get notified on views and downloads",
        saveChanges: "Save changes",
        saved: "Settings saved",
      },
    },
    lightbox: {
      close: "Close viewer",
      previous: "Previous photo",
      next: "Next photo",
      counter: (current: number, total: number) => `${current} / ${total}`,
      viewPhoto: (index: number) => `View photo ${index}`,
    },
    sidebar: {
      clientInfo: "Client info",
      summary: "Summary",
      shootDate: "Shoot date",
      location: "Location",
      notifyClient: "Notify client",
      exportReport: "Export report",
      archiveGallery: "Archive gallery",
      activityLog: "Activity log",
      viewProfile: "View profile",
      viewAllActivity: "View all activity",
      noActivity: "No client activity recorded yet.",
      notifySuccess: "Client notified",
      notifySuccessDescription: "An in-app notification was sent to the client.",
      exportSuccess: "Report exported",
      exportSuccessDescription: "Gallery analytics report downloaded.",
      archiveSuccess: "Gallery archived",
      archiveSuccessDescription: "This gallery is no longer visible to clients.",
      archiveConfirm: "Archive this gallery? Clients will lose access immediately.",
      archiveAlready: "This gallery is already archived.",
    },
  },
} as const;

export type GalleryCategoryFilter =
  | "all"
  | "wedding"
  | "portrait"
  | "graduation"
  | "commercial";

export type GalleryStatusFilter = "all" | "published" | "draft" | "archived";

export type GallerySortOption = "dateUploaded" | "name" | "photoCount";

export type GalleryDetailTab = "photos" | "delivery" | "analytics" | "settings";
