import { formatRwf } from "@/lib/currency";

export const NEW_BOOKING_COPY = {
  breadcrumbBookings: "Bookings",
  breadcrumbCurrent: "Create New",
  title: "New Booking",
  subtitle: "Configure your next professional shoot session.",
  saveDraft: "Save Draft",
  createBooking: "Create Booking",
  createAndSend: "Create Booking & Send Invite",
  clientInformation: "Client Information",
  selectExistingClient: "Select Existing Client",
  selectClientPlaceholder: "Choose a client...",
  addNewClient: "Add New Client",
  serviceDetails: "Service Details",
  shootPackage: "Shoot Package",
  schedulingLocation: "Scheduling & Location",
  shootDate: "Shoot Date",
  startTime: "Start Time",
  endTime: "End Time",
  locationName: "Location Name",
  address: "Address",
  locationPlaceholder: "Enter venue or studio name...",
  addressPlaceholder: "Street address, sector, Kigali...",
  paymentSettings: "Payment Settings",
  basePrice: "Base Price",
  depositRequired: "Deposit Required",
  paymentMethod: "Payment Method",
  autoApplyTax: "Auto-apply Tax (8.5%)",
  additionalDetails: "Additional Details",
  sessionNotes: "Session Notes",
  sessionNotesPlaceholder:
    "Add notes about lighting preferences, props, or special requests...",
  bookingSummary: "Booking Summary",
  reviewing: "Reviewing",
  summaryClient: "Client",
  summaryPackage: "Package",
  summaryDate: "Date",
  summaryLocation: "Location",
  noClientSelected: "No Client Selected",
  notSpecified: "Not Specified",
  subtotal: "Subtotal",
  estimatedTax: "Estimated Tax",
  totalCost: "Total Cost",
  depositDueNow: "Deposit Due Now",
  depositNote: "Remaining balance due before shoot date.",
  inviteDisclaimer:
    "An automated confirmation email will be sent to the client upon creation.",
  proTipTitle: "Pro Tip",
  proTipBody:
    "You can set up automated reminders for this booking in Settings under Workflow Automations.",
  money: (amount: number) => formatRwf(amount),
} as const;
