import { formatRwf } from "@/lib/currency";

export const SERVICE_CREATE_COPY = {
  breadcrumbServices: "Services",
  breadcrumbCurrent: "Create New",
  title: "Create New Package",
  subtitle:
    "Build photography packages that clients can book through your platform.",
  packageInformation: "Package Information",
  packageName: "Package Name",
  packageNamePlaceholder: "e.g. Minimalist Studio Session",
  category: "Category",
  status: "Status",
  statusDescription: "Set package visibility to clients",
  active: "Active",
  coverImage: "Cover Image",
  coverDropTitle: "Drop your cover image here",
  coverDropHint: "PNG, JPG or WEBP (Max 5MB)",
  pricing: "Pricing",
  packagePrice: "Package Price",
  depositPercentage: "Deposit Percentage",
  currency: "Currency",
  sessionDetails: "Session Details",
  sessionDuration: "Session Duration",
  numberOfPhotographers: "Number of Photographers",
  locationType: "Location Type",
  deliverables: "Deliverables",
  editedPhotos: "Number of Edited Photos",
  revisions: "Number of Revisions",
  onlineGallery: "Online Gallery Included",
  printDelivery: "Print Delivery Included",
  commercialLicense: "Full Commercial License",
  description: "Description",
  packageDescription: "Package Description",
  packageDescriptionPlaceholder:
    "Briefly describe what makes this package unique...",
  whatsIncluded: "What's Included",
  addCustom: "Add Custom",
  addItem: "Add Item",
  additionalNotes: "Additional Notes",
  additionalNotesPlaceholder:
    "e.g. Travel fees apply for locations outside Kigali city limits...",
  packagePreview: "Package Preview",
  preview: "Preview",
  publishPackage: "Publish Package",
  saveAsDraft: "Save as Draft",
  draftSaved: "Draft saved. You can return anytime to finish and publish.",
  publishNameRequired: "Please enter a package name before publishing.",
  untitledPackageName: "Untitled Package",
  autoSaved: "Changes auto-saved 2 mins ago",
  editBreadcrumbCurrent: "Edit Package",
  editTitle: "Edit Service Package",
  editSubtitle: "Update your photography package details and deliverables.",
  saveChanges: "Save Changes",
  cancel: "Cancel",
  notFound: "Service package not found.",
  lastUpdated: "Last updated 2 mins ago",
  proTipTitle: "Pro Tip: Deliverables",
  proTipBody:
    "Packages with 'Online Gallery' selected see 35% higher booking rates as it provides immediate value to your clients.",
  defaultPackageName: "Package Name",
  priceDisplay: (price: number) => formatRwf(price),
  categories: {
    wedding: "Wedding",
    portrait: "Portrait",
    commercial: "Commercial",
    editorial: "Editorial",
  },
  durations: {
    "30min": "30 Minutes",
    "1hr": "1 Hour",
    "2hr": "2 Hours",
    "4hr": "4 Hours",
    fullday: "Full Day",
  },
  locationTypes: {
    studio: "Studio",
    outdoor: "Outdoor",
    client: "Client Location",
    hybrid: "Hybrid",
  },
  currencies: {
    rwf: "RWF - Rwandan Franc",
  },
  defaultIncludes: [
    "Professional Retouching",
    "Online Private Gallery",
    "Full Printing Rights",
  ],
} as const;
