export const BOOKING_DETAIL_COPY = {
  back: "Back to bookings",
  breadcrumbBookings: "Bookings",
  rejectBooking: "Reject Booking",
  declineBooking: "Decline booking",
  approveBooking: "Approve Booking",
  viewCalendar: "View Calendar",
  markSessionComplete: "Mark Session Complete",
  requestedOn: (date: string, session: string) =>
    `Requested on ${date} • ${session}`,
  clientProfile: "Client Profile",
  preferredClientSince: (year: number) => `Preferred Client since ${year}`,
  contactEmail: "Email",
  contactPhone: "Phone",
  contactInstagram: "Instagram",
  eventLogistics: "Event Logistics",
  dateTime: "Date & Time",
  location: "Location",
  packageSelection: "Package Selection",
  allTaxesIncluded: "All taxes included",
  paymentVerification: "Payment Verification",
  requestNewReceipt: "Request New Receipt",
  reviewInPayments: "Review in Payments",
  paymentVerificationNote:
    "Approve or reject this payment from your Payments queue to keep records in one place.",
  management: "Management",
  verifyPayment: "Verify Payment",
  rejectSubmission: "Reject Submission",
  openPaymentsQueue: "Open Payments Queue",
  managementFooter: "Action will notify client via email",
  bookingTimeline: "Booking Timeline",
  internalNotes: "Internal Notes",
  notesPlaceholder:
    "Add a private note only you and your team can see...",
  saveNote: "Save Note",
  notFound: "Booking not found",
  galleryStatus: "Gallery Status",
  createGallery: "Create gallery",
  manageGallery: "Manage Gallery",
  galleryCreateHint:
    "Upload and deliver edited photos to your client from the linked gallery.",
  galleryBlockedHint:
    "Collect the final balance before creating or delivering the gallery.",
  releaseGalleryAnyway: "Release gallery anyway",
  galleryReleaseEnabled: "Gallery release override enabled",
  progressSteps: {
    bookingRequested: "Booking Requested",
    paymentSubmitted: "Payment Submitted",
    paymentVerified: "Payment Verified",
    sessionScheduled: "Session Scheduled",
    sessionCompleted: "Session Completed",
    galleryUploaded: "Gallery Uploaded",
    galleryDelivered: "Gallery Delivered",
  },
  galleryStages: {
    notStarted: "Not Started",
    editing: "Editing",
    ready: "Ready",
    delivered: "Delivered",
  },
  galleryActiveLabel: (stage: string) => `${stage} (Active)`,
  status: {
    pendingVerification: "Pending Verification",
    confirmed: "Confirmed",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
  },
} as const;
