export const GALLERY_CREATE_COPY = {
  breadcrumbGalleries: "Galleries",
  breadcrumbCreate: "Create New",
  breadcrumbEdit: "Edit Gallery",
  title: "Create New Gallery",
  editTitle: "Edit Gallery",
  subtitle: "Upload, organize, and prepare a gallery for client delivery.",
  editSubtitle: "Update gallery details, photos, and delivery settings.",
  saveDraft: "Save Draft",
  draftNameRequired: "Please enter a gallery name before saving a draft.",
  draftClientRequired: "Please select a client before saving a draft.",
  draftSaved: "Draft saved. You can return anytime from Galleries to continue editing.",
  createGallery: "Create Gallery",
  saveChanges: "Save Changes",
  cancel: "Cancel",
  galleryInformation: "Gallery Information",
  galleryName: "Gallery Name",
  galleryNamePlaceholder: "e.g. Niyonsaba Wedding",
  category: "Category",
  galleryDescription: "Gallery Description",
  galleryDescriptionPlaceholder:
    "Brief client-facing notes about this gallery...",
  clientAssignment: "Client Assignment",
  selectClient: "Select Client",
  selectClientPlaceholder: "Search or select a client...",
  relatedBooking: "Related Booking",
  relatedBookingPlaceholder: "Link to an existing booking",
  noBooking: "No linked booking",
  eliteClient: "Preferred Client",
  coverImage: "Cover Image",
  coverDropTitle: "Click to upload or drag cover image",
  coverReplaceTitle: "Cover image uploaded",
  coverDropHint: "Recommended size: 2400 x 1600px (Max 5MB)",
  uploadCover: "Upload cover",
  removeCover: "Remove",
  photoUpload: "Photo Upload",
  library: "Library",
  uploadPhotos: "Upload Photos",
  photoDropTitle: "Drag & drop photos here or browse files",
  photoDropHint: "JPG, PNG, or WebP up to 15MB each.",
  uploadProgress: (count: number, used: number, total: number) =>
    `${count.toLocaleString()} Photos • ${used} GB / ${total} GB Used`,
  deliverySettings: "Delivery Settings",
  visibility: "Visibility",
  visibilityOptions: {
    public: "Public Gallery",
    private: "Private (Client Only)",
    password: "Password Protected",
  },
  permissions: "Permissions",
  allowDownloads: "Allow Downloads",
  allowFavorites: "Allow Favorites",
  socialSharing: "Social Sharing",
  galleryStatus: "Gallery Status",
  statusSegments: {
    draft: "Draft",
    editing: "Editing",
    ready: "Ready for Delivery",
  },
  statusDescriptions: {
    draft: "Hidden from clients. Save and continue editing anytime.",
    editing: "In post-production. Upload and organize photos before release.",
    ready: "Ready for client review. Deliver from the gallery detail page when finished.",
  },
  lockedStatus: {
    delivered: "Delivered",
    archived: "Archived",
  },
  lockedStatusHints: {
    delivered:
      "This gallery has been delivered. Manage client access from the Delivery tab.",
    archived: "This gallery is archived and can no longer be edited.",
  },
  accessPin: "Gallery access PIN",
  accessPinPlaceholder: "e.g. 4821",
  accessPinHint: "Clients will need this PIN to open a password-protected gallery.",
  accessPinRequired: "Enter an access PIN for password-protected galleries.",
  summary: {
    title: "Gallery Summary",
    galleryName: "Gallery Name",
    client: "Client",
    category: "Category",
    photoCount: "Photo Count",
    storage: "Storage",
    status: "Status",
    footerNote:
      "Complete all required fields to enable delivery options for your client.",
    photos: (count: number) => `${count.toLocaleString()} Photos`,
    storageDisplay: (gb: number) => `${gb} GB`,
  },
  planUsage: {
    title: "Plan Usage",
    storageUsed: "Storage Used",
    remaining: (gb: number) => `You have ${gb} GB remaining on your Pro Plan.`,
    upgradeStorage: "Upgrade Storage",
  },
  quickLinks: {
    title: "Quick Links",
    previewGallery: "Preview Gallery",
    shareLink: "Share Link",
    hint: "Save a draft to preview or share this gallery.",
    linkCopied: "Gallery link copied to clipboard.",
  },
  categories: {
    wedding: "Wedding",
    portrait: "Portrait",
    graduation: "Graduation",
    commercial: "Commercial",
  },
  statusLabels: {
    draft: "Draft",
    editing: "Editing",
    ready: "Ready",
  },
} as const;
