import { formatRwf } from "@/lib/currency";

export const NEW_BOOKING_COPY = {
  breadcrumbBookings: "Bookings",
  breadcrumbCurrent: "Create new",
  title: "New booking",
  subtitle: "Configure your next professional shoot session.",
  saveDraft: "Save draft",
  createBooking: "Create booking",
  createAndSend: "Create booking & send invite",
  clientInformation: "Client information",
  selectExistingClient: "Select existing client",
  selectClientPlaceholder: "Choose a client...",
  addNewClient: "Add new client",
  serviceDetails: "Service details",
  shootPackage: "Shoot package",
  schedulingLocation: "Scheduling & location",
  shootDate: "Shoot date",
  startTime: "Start time",
  endTime: "End time",
  locationName: "Location name",
  address: "Address",
  locationPlaceholder: "Enter venue or studio name...",
  addressPlaceholder: "Street address, sector, Kigali...",
  paymentSettings: "Payment settings",
  basePrice: "Base price",
  depositRequired: "Deposit required",
  paymentMethod: "Payment method",
  autoApplyTax: "Auto-apply tax (8.5%)",
  additionalDetails: "Additional details",
  sessionNotes: "Session notes",
  sessionNotesPlaceholder:
    "Add notes about lighting preferences, props, or special requests...",
  bookingSummary: "Booking summary",
  reviewing: "Reviewing",
  summaryClient: "Client",
  summaryPackage: "Package",
  summaryDate: "Date",
  summaryLocation: "Location",
  noClientSelected: "No client selected",
  notSpecified: "Not specified",
  subtotal: "Subtotal",
  estimatedTax: "Estimated tax",
  totalCost: "Total cost",
  depositDueNow: "Deposit due now",
  depositNote: "Remaining balance due before shoot date.",
  inviteDisclaimer:
    "An automated confirmation email will be sent to the client upon creation.",
  proTipTitle: "Pro tip",
  proTipBody:
    "You can set up automated reminders for this booking in settings under workflow automations.",
  money: (amount: number) => formatRwf(amount),
} as const;
