export const ADD_CLIENT_COPY = {
  title: "Add New Client",
  description:
    "Create a client profile to start managing bookings, payments, and galleries.",
  personalInformation: "Personal Information",
  required: "Required",
  fullName: "Full Name",
  fullNamePlaceholder: "e.g. Grace Uwera",
  emailAddress: "Email Address",
  emailPlaceholder: "grace.uwera@gmail.com",
  phoneNumber: "Phone Number",
  phonePlaceholder: "+250 788 000 000",
  clientClassification: "Client Classification",
  clientCategory: "Client Category",
  categoryPlaceholder: "Select a category...",
  optionalInformation: "Optional Information",
  address: "Address",
  addressPlaceholder: "e.g. Nyarutarama, Kigali",
  notes: "Internal Notes",
  notesPlaceholder: "Add any internal notes about this client...",
  cancel: "Cancel",
  createClient: "Create Client",
  categories: {
    wedding: "Wedding",
    commercial: "Commercial",
    portrait: "Portrait",
    editorial: "Editorial",
  },
} as const;
