export const CALENDAR_COPY = {
  pageTitle: "Calendar",
  pageSubtitle: "View your schedule and upcoming sessions.",
  searchPlaceholder: "Search bookings, clients, or files...",
  today: "Today",
  views: {
    day: "Day",
    week: "Week",
    month: "Month",
  },
  navigation: {
    previous: {
      day: "Previous day",
      week: "Previous week",
      month: "Previous month",
    },
    next: {
      day: "Next day",
      week: "Next week",
      month: "Next month",
    },
  },
  dayViewHint: "Sessions scheduled for this day.",
  noSessionsDay: "No sessions scheduled for this day.",
  blockAvailability: "Block Availability",
  manageAvailability: "Manage Availability",
  manageAvailabilityHint:
    "Set working hours, booking limits, and blocked days for client scheduling.",
  closeAvailability: "Close",
  availabilitySaved: "Availability settings saved",
  blockDaySuccess: "Day blocked successfully",
  blockDayError: "Could not block this day",
  unblockDaySuccess: "Day is available for bookings again",
  unblockDayError: "Could not restore availability for this day",
  makeAvailable: "Make Available",
  unblockSelectedDay: "Unblock selected day",
  dayBlockedLabel: "Blocked",
  dayBlockedHint: "This day is blocked and unavailable for new client bookings.",
  upcomingBlockedDays: "Blocked days",
  noBlockedDays: "No manually blocked days in your schedule.",
  workingHours: "Working Hours",
  bookingLimits: "Booking Limits",
  bufferBetweenSessions: "Buffer between sessions",
  minNotice: "Minimum notice (hours)",
  maxDaysAhead: "Booking window (days)",
  maxSessionsPerDay: "Max sessions per day",
  saveAvailability: "Save Availability",
  blockSelectedDay: "Block selected day",
  noDaySelected: "Select a day on the calendar to block it.",
  dayStart: "Start",
  dayEnd: "End",
  shortWeekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  newBooking: "New Booking",
  availabilityOverview: "Availability Overview",
  almostFull: "Almost Full",
  slotsRemaining: (count: number, month: string) =>
    `${count} slots remaining in ${month}`,
  selectedSession: "Selected Day",
  noSessionsOnDay: "No sessions scheduled for this day.",
  paid: "Paid",
  time: "Time",
  package: "Package",
  location: "Location",
  reschedule: "Reschedule",
  edit: "Edit",
  complete: "Complete",
  cancel: "Cancel",
  upcomingNext: "Upcoming Sessions",
  sessionStatus: {
    confirmed: "Confirmed",
    awaitingPayment: "Awaiting Payment",
    paid: "Paid",
    completed: "Completed",
  },
} as const;

export const CALENDAR_WEEKDAYS = [
  "MON",
  "TUE",
  "WED",
  "THU",
  "FRI",
  "SAT",
  "SUN",
] as const;
