export const BOOKING_DETAIL_COPY = {
  back: "Back to bookings",
  breadcrumbBookings: "Bookings",
  rejectBooking: "Reject booking",
  declineBooking: "Decline booking",
  approveBooking: "Approve booking",
  viewCalendar: "View calendar",
  markSessionComplete: "Mark session complete",
  requestedOn: (date: string, session: string) =>
    `Requested on ${date} • ${session}`,
  clientProfile: "Client profile",
  preferredClientSince: (year: number) => `Preferred Client since ${year}`,
  contactEmail: "Email",
  contactPhone: "Phone",
  contactInstagram: "Instagram",
  eventLogistics: "Event logistics",
  dateTime: "Date & time",
  location: "Location",
  packageSelection: "Package selection",
  allTaxesIncluded: "All taxes included",
  paymentVerification: "Payment verification",
  requestNewReceipt: "Request new receipt",
  reviewInPayments: "Review in payments",
  paymentVerificationNote:
    "Approve or reject this payment from your payments queue to keep records in one place.",
  management: "Management",
  verifyPayment: "Verify payment",
  rejectSubmission: "Reject submission",
  openPaymentsQueue: "Open payments queue",
  managementFooter: "Action will notify client via email",
  bookingTimeline: "Booking timeline",
  internalNotes: "Internal notes",
  notesPlaceholder:
    "Add a private note only you and your team can see...",
  saveNote: "Save note",
  notFound: "Booking not found",
  galleryStatus: "Gallery status",
  createGallery: "Create gallery",
  manageGallery: "Manage gallery",
  galleryCreateHint:
    "Upload and deliver edited photos to your client from the linked gallery.",
  galleryBlockedHint:
    "Collect the final balance before creating or delivering the gallery.",
  releaseGalleryAnyway: "Release gallery anyway",
  galleryReleaseEnabled: "Gallery release override enabled",
  progressSteps: {
    bookingRequested: "Booking requested",
    paymentSubmitted: "Payment submitted",
    paymentVerified: "Payment verified",
    sessionScheduled: "Session scheduled",
    sessionCompleted: "Session completed",
    galleryUploaded: "Gallery uploaded",
    galleryDelivered: "Gallery delivered",
  },
  galleryStages: {
    notStarted: "Not started",
    editing: "Editing",
    ready: "Ready",
    delivered: "Delivered",
  },
  galleryActiveLabel: (stage: string) => `${stage} (Active)`,
  status: {
    pendingVerification: "Pending verification",
    confirmed: "Confirmed",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
  },
} as const;
