export const GALLERY_CREATE_COPY = {
  breadcrumbGalleries: "Galleries",
  breadcrumbCreate: "Create new",
  breadcrumbEdit: "Edit gallery",
  title: "Create new gallery",
  editTitle: "Edit gallery",
  subtitle: "Upload, organize, and prepare a gallery for client delivery.",
  editSubtitle: "Update gallery details, photos, and delivery settings.",
  saveDraft: "Save draft",
  draftNameRequired: "Please enter a gallery name before saving a draft.",
  draftClientRequired: "Please select a client before saving a draft.",
  draftSaved: "Draft saved. You can return anytime from galleries to continue editing.",
  createGallery: "Create gallery",
  saveChanges: "Save changes",
  cancel: "Cancel",
  galleryInformation: "Gallery information",
  galleryName: "Gallery name",
  galleryNamePlaceholder: "e.g. Niyonsaba Wedding",
  category: "Category",
  galleryDescription: "Gallery description",
  galleryDescriptionPlaceholder:
    "Brief client-facing notes about this gallery...",
  clientAssignment: "Client assignment",
  selectClient: "Select client",
  selectClientPlaceholder: "Search or select a client...",
  relatedBooking: "Related booking",
  relatedBookingPlaceholder: "Link to an existing booking",
  noBooking: "No linked booking",
  eliteClient: "Preferred client",
  coverImage: "Cover image",
  coverDropTitle: "Click to upload or drag cover image",
  coverReplaceTitle: "Cover image uploaded",
  coverDropHint: "Recommended size: 2400 x 1600px (Max 5MB)",
  uploadCover: "Upload cover",
  removeCover: "Remove",
  photoUpload: "Photo upload",
  library: "Library",
  uploadPhotos: "Upload photos",
  photoDropTitle: "Drag & drop photos here or browse files",
  photoDropHint: "JPG, PNG, or WebP up to 15MB each.",
  uploadProgress: (count: number) =>
    `${count.toLocaleString()} ${count === 1 ? "photo" : "photos"} ready to upload`,
  deliverySettings: "Delivery settings",
  visibility: "Visibility",
  visibilityOptions: {
    public: "Public gallery",
    private: "Private (Client only)",
    password: "Password protected",
  },
  permissions: "Permissions",
  allowDownloads: "Allow downloads",
  allowFavorites: "Allow favorites",
  socialSharing: "Social sharing",
  galleryStatus: "Gallery status",
  statusSegments: {
    draft: "Draft",
    editing: "Editing",
    ready: "Ready for delivery",
  },
  statusDescriptions: {
    draft: "Hidden from clients. Save and continue editing anytime.",
    editing: "In post-production. Upload and organize photos before release.",
    ready: "Ready for client review. Deliver from the gallery detail page when finished.",
  },
  lockedStatus: {
    delivered: "Delivered",
    archived: "Archived",
  },
  lockedStatusHints: {
    delivered:
      "This gallery has been delivered. Manage client access from the delivery tab.",
    archived: "This gallery is archived and can no longer be edited.",
  },
  accessPin: "Gallery access PIN",
  accessPinPlaceholder: "e.g. 4821",
  accessPinHint: "Clients will need this PIN to open a password-protected gallery.",
  accessPinRequired: "Enter an access PIN for password-protected galleries.",
  summary: {
    title: "Gallery summary",
    galleryName: "Gallery name",
    client: "Client",
    category: "Category",
    photoCount: "Photo count",
    status: "Status",
    footerNote:
      "Complete all required fields to enable delivery options for your client.",
    photos: (count: number) => `${count.toLocaleString()} Photos`,
  },
  quickLinks: {
    title: "Quick links",
    previewGallery: "Preview gallery",
    shareLink: "Share link",
    hint: "Save a draft to preview or share this gallery.",
    linkCopied: "Gallery link copied to clipboard.",
  },
  categories: {
    wedding: "Wedding",
    portrait: "Portrait",
    graduation: "Graduation",
    commercial: "Commercial",
  },
  statusLabels: {
    draft: "Draft",
    editing: "Editing",
    ready: "Ready",
  },
} as const;
