export const ANALYTICS_COPY = {
  title: "Analytics overview",
  subtitle: "Track your studio performance and growth metrics.",
  dateRange: "Last 30 days",
  dateRanges: {
    "7": "Last 7 Days",
    "30": "Last 30 Days",
    "90": "Last 90 Days",
    year: "This year",
  },
  kpis: {
    totalRevenue: "Total revenue",
    sessionsCompleted: "Sessions completed",
    repeatClients: "Repeat clients",
    conversionRate: "Conversion rate",
  },
  revenueOverTime: "Revenue over time",
  monthly: "Monthly",
  weekly: "Weekly",
  bookingsVolume: "Bookings volume",
  totalShoots: (total: number) => `Total: ${total} Shoots`,
  popularServices: "Popular services",
  topClients: "Top clients",
  columns: {
    serviceName: "Service name",
    bookings: "Bookings",
    revenueShare: "Revenue share",
  },
  sessions: (count: number) => `${count} sessions`,
  clientStatus: {
    highValue: "High value",
    goldStatus: "Gold status",
    loyalMember: "Loyal member",
  },
} as const;
